//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillersLawnService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.tblInvoicesLineItems = new HashSet<InvoiceLineItem>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeFName { get; set; }
        public string EmployeeLName { get; set; }
        public string EmployeePhoneNum { get; set; }
        public string EmployeeState { get; set; }
        public string EmployeeCity { get; set; }
        public string EmployeeAddress { get; set; }
        public string EmployeeZipCode { get; set; }
        public decimal EmployeeCurrentPay { get; set; }
    
        public virtual State tblState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLineItem> tblInvoicesLineItems { get; set; }
    }
}
