//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillersLawnService
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineItem
    {
        public int InvLineItemDetailID { get; set; }
        public int InvoiceID { get; set; }
        public int ServiceID { get; set; }
        public int EmployeeID { get; set; }
        public int ServiceNumOfHours { get; set; }
    
        public virtual Employee tblEmployee { get; set; }
        public virtual Invoice tblInvoice { get; set; }
        public virtual Service tblService { get; set; }
    }
}
