//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillersLawnService
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLineItem
    {
        public int POID { get; set; }
        public int EquipmentID { get; set; }
        public int EquipmentQty { get; set; }
        public decimal LineItemCost { get; set; }
    
        public virtual Equipment tblEquipment { get; set; }
        public virtual PurchaseOrder tblPurchaseOrder { get; set; }
    }
}
